# Generated by Django 4.2.3 on 2023-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='marchand_created',
            field=models.BooleanField(default=False),
        ),
    ]
