# Generated by Django 4.2.3 on 2023-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='token',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporate',
            name='marchand_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_connection_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='marchand_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='pwd',
            field=models.CharField(default='', max_length=200),
        ),
    ]
