# Generated by Django 4.2.3 on 2023-10-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0002_agent_token_corporate_marchand_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='marchand_created',
            field=models.BooleanField(default=False),
        ),
    ]
