# Generated by Django 4.2.3 on 2023-07-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0002_remove_invoiceproduct_price_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='products',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
    ]
